language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - python3 -m unittest tests/*_unittest.py
  - docker build -t test:latest -f Dockerfile

deploy:
  - provider: script
    script: make docker-buildx $DOCKER_USERNAME $DOCKER_PASSWORD dev --push
    on:
      all_branches: true

