language: python
python:
  - "3.9"

services:
  - docker    

dist: focal
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get update
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo apt-get install -y qemu-user-static binfmt-support
  - docker buildx create --use

install:
  - pip install -r requirements.txt

script:
  - python3 -m unittest tests/*_unittest.py
  - docker build -t test:latest -f Dockerfile

deploy:
  - provider: script
    script: make docker-buildx $DOCKER_USERNAME $DOCKER_PASSWORD dev --push
    on:
      all_branches: true
